<div class="row">
<?php echo Form::open('usuarios/guardar', 'POST' ,'class="col s12"'); ?>
    <div class="row">
        <div class="input-field col s6">
            <?php echo Form::text('usuarios.nombres'); ?>
            <?php echo Form::label('Nombres','nombres'); ?>
        </div>
        <div class="input-field col s6">
            <?php echo Form::text('usuarios.apellidos'); ?>
            <?php echo Form::label('Apellidos','apellidos'); ?>
        </div>
    </div>
    <div class="row">
        <div class="input-field col s6">
            <?php echo Form::text('usuarios.telefono'); ?>
            <?php echo Form::label('Telefono','telefono'); ?>
        </div>
        <div class="input-field col s6">
            <?php echo Form::text('usuarios.dui'); ?>
            <?php echo Form::label('Dui','dui'); ?>
        </div>
        <div class="input-field col s6">
            <?php echo Form::date('usuarios.fecha_de_nacimiento'); ?>
            <?php echo Form::label('Fecha','fecha_de_nacimiento'); ?>
         </div>
         <div class="input-field col s6">
            <?php echo Form::text('usuarios.email'); ?>
            <?php echo Form::label('Email','email'); ?>
        </div>  
    <div class="row">
        <?php echo Form::submit('Guardar','class="btn indigo darken-4"'); ?>
        <?php echo Form::reset('Limpiar','class="btn pink"'); ?>
        </div>
    </div>
<?php echo Form::close() ?>
</div>